//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Converter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategorySet
    {
        public CategorySet()
        {
            this.Category = new HashSet<Category>();
        }
    
        public int Id { get; set; }
        public string Category_Type { get; set; }
    
        public virtual ICollection<Category> Category { get; set; }
    }
}
