//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Converter_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Constants = new HashSet<Constant>();
        }
    
        public int Id { get; set; }
        public string Category1 { get; set; }
    
        public virtual ICollection<Constant> Constants { get; set; }
    }
}
